name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build & Test
        run: mvn clean test

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq libxml2-utils

      - name: Copy reports
        run: |
          mkdir -p devsecops-reporter/reports
          cp target/site/jacoco/jacoco.xml devsecops-reporter/reports/

      - name: Run DevSecOps reporter
        run: |
          cd devsecops-reporter
          chmod +x *.sh parsers/*.sh
          bash reporter.sh
          bash generate_html.sh
          bash send_telegram.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
